version: '3'
services:
  nats:
    restart: always
    image: nats:2.7.3
    container_name: nats
    ports:
      - "4224:4222/tcp"
      - "8224:8222/tcp"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./conf/nats-server.conf:/nats-server.conf
      - ./data:/nats/storage
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 512M
