[hk4e]
client_proto_proxy_enable = false
game_data_config_path = "./game_data_config"
gacha_history_server = "https://hk4e.flswld.com/api/v1"
load_scene_lua_config = true # 是否加载场景详情LUA配置数据

[logger]
level = "DEBUG"
mode = "CONSOLE"
track = true
max_size = 10485760

[database]
url = "mongodb://mongo:27017"

[redis]
addr = "redis://redis:6379"
password = ""

[mq]
nats_url = "nats://nats:4222"
