version: '3'
services:
  mongo:
    restart: always
    image: mongo:5.0.5
    container_name: mongo
    ports:
      - "27017:27017/tcp"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./data:/data/db
    deploy:
      resources:
        limits:
          cpus: '4.00'
          memory: 512M
